/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ButtonGroup;

/**
 *
 * @author felipegutierrez
 */
public class VerRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerRegistro
     */
    public VerRegistro() {
        initComponents();
        ButtonGroup radioGrupo=new ButtonGroup();
        radioGrupo.add(rdPendientes);
        radioGrupo.add(rdRango);
        radioGrupo.add(rbVerTodos);
        rbVerTodos.setSelected(true);
        txbFechaIni.setEnabled(false);
        txbFechaFin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbVerTodos = new javax.swing.JRadioButton();
        rdPendientes = new javax.swing.JRadioButton();
        rdRango = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txbFechaIni = new com.toedter.calendar.JDateChooser();
        txbFechaFin = new com.toedter.calendar.JDateChooser();

        setClosable(true);

        rbVerTodos.setText("Ver Todos");
        rbVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerTodosActionPerformed(evt);
            }
        });

        rdPendientes.setText("Pendientes");
        rdPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPendientesActionPerformed(evt);
            }
        });

        rdRango.setText("Rango de Fechas");
        rdRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRangoActionPerformed(evt);
            }
        });

        jButton1.setText("Ver");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Proveedor", "Monto", "Fecha Pago", "Descripcion", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rbVerTodos)
                .addGap(18, 18, 18)
                .addComponent(rdPendientes)
                .addGap(18, 18, 18)
                .addComponent(rdRango)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txbFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(txbFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbVerTodos)
                        .addComponent(rdPendientes)
                        .addComponent(rdRango)
                        .addComponent(jButton1))
                    .addComponent(txbFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRangoActionPerformed
        
        txbFechaIni.setEnabled(true);
        txbFechaFin.setEnabled(true);
    }//GEN-LAST:event_rdRangoActionPerformed

    private void rdPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPendientesActionPerformed
        
        txbFechaIni.setEnabled(false);
        txbFechaFin.setEnabled(false);
        
    }//GEN-LAST:event_rdPendientesActionPerformed

    private void rbVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerTodosActionPerformed
        
        txbFechaIni.setEnabled(false);
        txbFechaFin.setEnabled(false);
        
        
    }//GEN-LAST:event_rbVerTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbVerTodos;
    private javax.swing.JRadioButton rdPendientes;
    private javax.swing.JRadioButton rdRango;
    private com.toedter.calendar.JDateChooser txbFechaFin;
    private com.toedter.calendar.JDateChooser txbFechaIni;
    // End of variables declaration//GEN-END:variables
}
